alter table public.premium_questions
  add column if not exists question_type text not null default 'multiple-choice',
  add column if not exists answer text;

alter table public.premium_questions
  alter column options drop not null,
  alter column answer_index drop not null;

alter table public.premium_questions
  drop constraint if exists premium_questions_options_check,
  drop constraint if exists premium_questions_answer_index_check,
  drop constraint if exists premium_questions_question_type_check,
  drop constraint if exists premium_questions_shape_check;

alter table public.premium_questions
  add constraint premium_questions_question_type_check
    check (question_type in ('direct', 'multiple-choice')),
  add constraint premium_questions_shape_check
    check (
      (
        question_type = 'direct'
        and answer is not null
        and btrim(answer) <> ''
        and options is null
        and answer_index is null
      )
      or
      (
        question_type = 'multiple-choice'
        and answer is null
        and jsonb_typeof(options) = 'array'
        and jsonb_array_length(options) >= 2
        and answer_index is not null
        and answer_index >= 0
        and answer_index < jsonb_array_length(options)
      )
    );

insert into public.premium_questions
  (id, category_id, question_type, question, options, answer_index, answer, rationale, source, difficulty, keywords, content_version)
values
  (
    'uio-015',
    'uio',
    'direct',
    'Uprava za indirektno oporezivanje je samostalna upravna organizacija koja za svoj rad putem Upravnog odbora odgovara:',
    null,
    null,
    'Savjetu ministara BiH.',
    'Tačan odgovor prema izvornom dokumentu: Savjetu ministara BiH.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'samostalna', 'upravna', 'organizacija', 'svoj', 'putem', 'upravnog', 'odbora', 'odgovara']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-016',
    'uio',
    'direct',
    'Sjedište Uprave je u:',
    null,
    null,
    'Banja Luci.',
    'Tačan odgovor prema izvornom dokumentu: Banja Luci.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'sjedište', 'uprave', 'banja', 'luci']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-017',
    'uio',
    'direct',
    'Pod osnovnom djelatnošću UIO podrazumijevaju se poslovi i zadaci:',
    null,
    null,
    'Carinskog nadzora, carinjenja robe, kontrole putnika i prevoznih sredstava, revizija i kontrola naplate prihoda.',
    'Tačan odgovor prema izvornom dokumentu: Carinskog nadzora, carinjenja robe, kontrole putnika i prevoznih sredstava, revizija i kontrola naplate prihoda.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'osnovnom', 'djelatnošću', 'podrazumijevaju', 'poslovi', 'zadaci', 'carinskog', 'nadzora', 'carinjenja']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-018',
    'uio',
    'direct',
    'Korisnici prihoda od indirektnih poreza su:',
    null,
    null,
    'Država Bosna i Hercegovina, Federacija BiH, Republika Srpska i Brčko distrikt BiH.',
    'Tačan odgovor prema izvornom dokumentu: Država Bosna i Hercegovina, Federacija BiH, Republika Srpska i Brčko distrikt BiH.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'korisnici', 'prihoda', 'indirektnih', 'poreza', 'država', 'federacija', 'republika', 'srpska']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-019',
    'uio',
    'direct',
    'Glavna kancelarija UIO obavlja sljedeće poslove:',
    null,
    null,
    'vodi drugostepeni upravni postupak i prvostepeni upravni postupak kad je to određeno zakonom.',
    'Tačan odgovor prema izvornom dokumentu: vodi drugostepeni upravni postupak i prvostepeni upravni postupak kad je to određeno zakonom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'glavna', 'kancelarija', 'obavlja', 'poslove', 'vodi', 'drugostepeni', 'upravni', 'postupak']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-020',
    'uio',
    'direct',
    'Glavna kancelarija UIO obavlja sljedeće poslove:',
    null,
    null,
    'Vodi jedinstveni račun i vrši naplatu prihoda po osnovu indirektnih poreza, doznačavenje i raspodjelu prihoda po osnovu indirektnih poreza na način regulisan zakonom.',
    'Tačan odgovor prema izvornom dokumentu: Vodi jedinstveni račun i vrši naplatu prihoda po osnovu indirektnih poreza, doznačavenje i raspodjelu prihoda po osnovu indirektnih poreza na način regulisan zakonom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'glavna', 'kancelarija', 'obavlja', 'poslove', 'vodi', 'jedinstveni', 'račun', 'vrši']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-021',
    'uio',
    'direct',
    'Glavna kancelarija UIO obavlja sljedeće poslove:',
    null,
    null,
    'Vodi jedinstveni registar obveznika indirektnih poreza i dodjeljuje im odgovarajući identifikacioni broj u postupku registracije',
    'Tačan odgovor prema izvornom dokumentu: Vodi jedinstveni registar obveznika indirektnih poreza i dodjeljuje im odgovarajući identifikacioni broj u postupku registracije',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'glavna', 'kancelarija', 'obavlja', 'poslove', 'vodi', 'jedinstveni', 'registar', 'obveznika']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-022',
    'uio',
    'direct',
    'Regionalni centri, putem svojih organizacionih jedinica obavljaju poslove:',
    null,
    null,
    'Carinjenja robe, obračun i naplatu prihoda.',
    'Tačan odgovor prema izvornom dokumentu: Carinjenja robe, obračun i naplatu prihoda.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'regionalni', 'centri', 'putem', 'svojih', 'organizacionih', 'jedinica', 'obavljaju', 'poslove']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-023',
    'uio',
    'direct',
    'Zasnivanjem radnog odnosa sa srednjom stručnom spremom, zaposleni stiče status:',
    null,
    null,
    'Zaposlenika.',
    'Tačan odgovor prema izvornom dokumentu: Zaposlenika.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zasnivanjem', 'radnog', 'odnosa', 'srednjom', 'stručnom', 'spremom', 'zaposleni', 'stiče']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-024',
    'uio',
    'direct',
    'Zaposleni u Upravi za indirektno oporezivanje su:',
    null,
    null,
    'Državni službenici i zaposlenici.',
    'Tačan odgovor prema izvornom dokumentu: Državni službenici i zaposlenici.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'upravi', 'državni', 'službenici', 'zaposlenici']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-025',
    'uio',
    'direct',
    'Na zaposlenike se primjenjuju odredbe:',
    null,
    null,
    'Zakona o radu u institucijama BiH.',
    'Tačan odgovor prema izvornom dokumentu: Zakona o radu u institucijama BiH.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposlenike', 'primjenjuju', 'odredbe', 'zakona', 'radu', 'institucijama']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-026',
    'uio',
    'multiple-choice',
    'Odluku o premještaju zaposlenih u Upravi za indirektno oporezivanje donosi:',
    '["Direktor,","Agencija za državnu službu BiH,","Pomoćnik direktora."]'::jsonb,
    0,
    null,
    'Tačan odgovor prema izvornom dokumentu: Direktor',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'odluku', 'premještaju', 'zaposlenih', 'upravi', 'donosi', 'direktor']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-027',
    'uio',
    'direct',
    'Obavezu polaganja stručnog ispita za rad na poslovima indirektnih poreza zaposlenih u Upravi za indirektno oporezivanje imaju:',
    null,
    null,
    'Zaposleni koji je zasnovao radni odnos na neodređeno vrijeme i raspoređen je na radno mjesto za obavljanje poslova iz osnovne djelatnosti.',
    'Tačan odgovor prema izvornom dokumentu: Zaposleni koji je zasnovao radni odnos na neodređeno vrijeme i raspoređen je na radno mjesto za obavljanje poslova iz osnovne djelatnosti.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'obavezu', 'polaganja', 'stručnog', 'ispita', 'poslovima', 'indirektnih', 'poreza', 'zaposlenih']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-028',
    'uio',
    'direct',
    'Službeno odijelo je dužan da nosi:',
    null,
    null,
    'Zaposleni koji obavlja poslove i zadatke iz osnovne djelatnosti i drugi zaposleni kad to zahtijeva priroda posla',
    'Tačan odgovor prema izvornom dokumentu: Zaposleni koji obavlja poslove i zadatke iz osnovne djelatnosti i drugi zaposleni kad to zahtijeva priroda posla',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'službeno', 'odijelo', 'dužan', 'nosi', 'zaposleni', 'obavlja', 'poslove', 'zadatke']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-029',
    'uio',
    'direct',
    'Ko ima pravo na radno odijelo i zaštitnu opremu:',
    null,
    null,
    'Zaposleni koji obavljaju pregled robe u prevoznim i prenosnim sredstvima, carinskim skladištima i drugim prostorima, carinskim laboratorijama, uređajima za kontrolu robe i putnika i vrše druge stručno-tehničke poslove.',
    'Tačan odgovor prema izvornom dokumentu: Zaposleni koji obavljaju pregled robe u prevoznim i prenosnim sredstvima, carinskim skladištima i drugim prostorima, carinskim laboratorijama, uređajima za kontrolu robe i putnika i vrše druge stručno-tehničke poslove.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'pravo', 'radno', 'odijelo', 'zaštitnu', 'opremu', 'zaposleni', 'obavljaju', 'pregled']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-030',
    'uio',
    'direct',
    'Prema Zakonu o UIO, ovlašćeno službeno lice je:',
    null,
    null,
    'Lice koje obavlja poslove iz osnovne djelatnosti UIO i lica koja imaju određena ovlašćenja u skladu sa zakonima koji regulišu krivične postupke u Bosni i Hercegovini.',
    'Tačan odgovor prema izvornom dokumentu: Lice koje obavlja poslove iz osnovne djelatnosti UIO i lica koja imaju određena ovlašćenja u skladu sa zakonima koji regulišu krivične postupke u Bosni i Hercegovini.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'prema', 'zakonu', 'ovlašćeno', 'službeno', 'lice', 'obavlja', 'poslove', 'osnovne']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-031',
    'uio',
    'direct',
    'Prema Zakonu o UIO, ovlašćeno službeno lice je ovlašćeno da:',
    null,
    null,
    'Izvrši pretres lica koja dolaze ili napuštaju carinsko područje slobodnu zonu ili carinsko skladište ili ostaju u tranzitnom području luka ili aerodroma, ako postoje osnovi sumnje o prikrivanju robe koja podliježe carinskom nadzoru.',
    'Tačan odgovor prema izvornom dokumentu: Izvrši pretres lica koja dolaze ili napuštaju carinsko područje slobodnu zonu ili carinsko skladište ili ostaju u tranzitnom području luka ili aerodroma, ako postoje osnovi sumnje o prikrivanju robe koja podliježe carinskom nadzoru.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'prema', 'zakonu', 'ovlašćeno', 'službeno', 'lice', 'izvrši', 'pretres', 'lica']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-032',
    'uio',
    'direct',
    'Prema Zakonu o UIO, ovlašćeno službeno lice je ovlašćeno da:',
    null,
    null,
    'Privremeno zadrži robu i prevozno sredstvo nad kojim nije sproveden postupak ili nije sproveden u skladu sa zakonskim propisima.',
    'Tačan odgovor prema izvornom dokumentu: Privremeno zadrži robu i prevozno sredstvo nad kojim nije sproveden postupak ili nije sproveden u skladu sa zakonskim propisima.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'prema', 'zakonu', 'ovlašćeno', 'službeno', 'lice', 'privremeno', 'zadrži', 'robu']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-033',
    'uio',
    'direct',
    'Prema Zakonu o UIO, ovlašćeno službeno lice je ovlašćeno da:',
    null,
    null,
    'Vrši kontrolu lica koja dolaze ili napuštaju carinsko područje, slobodnu zonu ili carinsko skladište ili ostaju u tranzitnom području luka ili aerodroma, vrši identifikaciju lica, zahtijeva prijavu i predočavanje njihovog ličnog prtljaga, izvrši pregled ličnog prtljaga, a po potrebi i njegov pretres.',
    'Tačan odgovor prema izvornom dokumentu: Vrši kontrolu lica koja dolaze ili napuštaju carinsko područje, slobodnu zonu ili carinsko skladište ili ostaju u tranzitnom području luka ili aerodroma, vrši identifikaciju lica, zahtijeva prijavu i predočavanje njihovog ličnog prtljaga, izvrši pregled ličnog prtljaga, a po potrebi i njegov pretres.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'prema', 'zakonu', 'ovlašćeno', 'službeno', 'lice', 'vrši', 'kontrolu', 'lica']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-034',
    'uio',
    'direct',
    'Prilikom preduzimanja radnji u skladu sa ovlašćenjima, ovlašćeno službeno lice je dužno:',
    null,
    null,
    'Da vodi računa da ne prouzrokuje veću štetu nego što je neophodno da bi se postigla njegova svrha.',
    'Tačan odgovor prema izvornom dokumentu: Da vodi računa da ne prouzrokuje veću štetu nego što je neophodno da bi se postigla njegova svrha.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'prilikom', 'preduzimanja', 'radnji', 'skladu', 'ovlašćenjima', 'ovlašćeno', 'službeno', 'lice']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-035',
    'uio',
    'direct',
    'Zaposleni u UIO ima dužnost i obavezu:',
    null,
    null,
    'Da vrši poslove koji su mu predviđeni opisom radnog mjesta, te druge zadatke povjerene od rukovodioca.',
    'Tačan odgovor prema izvornom dokumentu: Da vrši poslove koji su mu predviđeni opisom radnog mjesta, te druge zadatke povjerene od rukovodioca.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'dužnost', 'obavezu', 'vrši', 'poslove', 'predviđeni', 'opisom', 'radnog']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-036',
    'uio',
    'direct',
    'Zaposleni u UIO ima dužnost i obavezu:',
    null,
    null,
    'Da poštuje radno vrijeme i da ga koristi za izvršavanje svojih službenih dužnosti.',
    'Tačan odgovor prema izvornom dokumentu: Da poštuje radno vrijeme i da ga koristi za izvršavanje svojih službenih dužnosti.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'dužnost', 'obavezu', 'poštuje', 'radno', 'vrijeme', 'koristi', 'izvršavanje']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-037',
    'uio',
    'direct',
    'Kodeks ponašanja zaposlenih u UIO donosi:',
    null,
    null,
    'Direktor.',
    'Tačan odgovor prema izvornom dokumentu: Direktor.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'kodeks', 'ponašanja', 'zaposlenih', 'donosi', 'direktor']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-038',
    'uio',
    'direct',
    'Kodeksom ponašanja zaposlenih u UIO se :',
    null,
    null,
    'Utvrđuju pravila ponašanja zaposlenih u UIO, tokom i van radnog vremena.',
    'Tačan odgovor prema izvornom dokumentu: Utvrđuju pravila ponašanja zaposlenih u UIO, tokom i van radnog vremena.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'kodeksom', 'ponašanja', 'zaposlenih', 'utvrđuju', 'pravila', 'tokom', 'radnog', 'vremena']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-039',
    'uio',
    'direct',
    'Ko zaposlenog treba upoznati sa Kodeksom ponašanja zaposlenih u UIO:',
    null,
    null,
    'Neposredni rukovodilac.',
    'Tačan odgovor prema izvornom dokumentu: Neposredni rukovodilac.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposlenog', 'treba', 'upoznati', 'kodeksom', 'ponašanja', 'zaposlenih', 'neposredni', 'rukovodilac']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-040',
    'uio',
    'direct',
    'Kada se zaposleni treba upoznati sa Kodeksom ponašanja zaposlenih u UIO:',
    null,
    null,
    'Odmah po zasnivanju radnog odnosa.',
    'Tačan odgovor prema izvornom dokumentu: Odmah po zasnivanju radnog odnosa.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'treba', 'upoznati', 'kodeksom', 'ponašanja', 'zaposlenih', 'odmah', 'zasnivanju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-041',
    'uio',
    'direct',
    'Obavezu da obezbijedi primjenu Kodeksa ponašanja zaposlenih u UIO ima:',
    null,
    null,
    'Neposredni rukovodilac.',
    'Tačan odgovor prema izvornom dokumentu: Neposredni rukovodilac.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'obavezu', 'obezbijedi', 'primjenu', 'kodeksa', 'ponašanja', 'zaposlenih', 'neposredni', 'rukovodilac']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-042',
    'uio',
    'direct',
    'Zaposleni bez posebnog odobrenja direktora:',
    null,
    null,
    'Ne smije obavljati dodatnu aktivnost van UIO, bez obzira da li za to ostvaruje naknadu ili ne, ako obavljanje takvih aktivnosti dovodi u pitanje nepristrasnost u obavljanju službenih dužnosti.',
    'Tačan odgovor prema izvornom dokumentu: Ne smije obavljati dodatnu aktivnost van UIO, bez obzira da li za to ostvaruje naknadu ili ne, ako obavljanje takvih aktivnosti dovodi u pitanje nepristrasnost u obavljanju službenih dužnosti.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'posebnog', 'odobrenja', 'direktora', 'smije', 'obavljati', 'dodatnu', 'aktivnost']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-043',
    'uio',
    'direct',
    'Izjavu o nespojivosti sa dužnostima zaposleni popunjava:',
    null,
    null,
    'Prilikom zasnivanja radnog odnosa u Upravi i na zahtjev direktora.',
    'Tačan odgovor prema izvornom dokumentu: Prilikom zasnivanja radnog odnosa u Upravi i na zahtjev direktora.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'izjavu', 'nespojivosti', 'dužnostima', 'zaposleni', 'popunjava', 'prilikom', 'zasnivanja', 'radnog']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-044',
    'uio',
    'direct',
    'Zaposleni popunjava obrazac o svojoj imovini i imovini članova uže porodice, o svojim aktivnostima, djelatnostima i funkcijama koje obavljaju članovi uže porodice i potpisuje izjavu kojom se odobrava provjeravanje tačnosti datih informacija:',
    null,
    null,
    'Prilikom zasnivanja radnog odnosa i na početku svake kalendarske godine.',
    'Tačan odgovor prema izvornom dokumentu: Prilikom zasnivanja radnog odnosa i na početku svake kalendarske godine.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'popunjava', 'obrazac', 'svojoj', 'imovini', 'članova', 'porodice', 'svojim']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-045',
    'uio',
    'direct',
    'Pravo komunikacije sa sredstvima javnog informisanja u ime UIO imaju:',
    null,
    null,
    'Zaposleni iz Odjeljenja za komunikacije i međunarodnu saradnju koji su posebno ovlašćeni i zaposleni iz drugih organizacionih jedinica uz posebno odobrenje direktora.',
    'Tačan odgovor prema izvornom dokumentu: Zaposleni iz Odjeljenja za komunikacije i međunarodnu saradnju koji su posebno ovlašćeni i zaposleni iz drugih organizacionih jedinica uz posebno odobrenje direktora.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'pravo', 'komunikacije', 'sredstvima', 'javnog', 'informisanja', 'imaju', 'zaposleni', 'odjeljenja']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-046',
    'uio',
    'direct',
    'Upotreba mobilnog telefona je zabranjena:',
    null,
    null,
    'Zaposlenim u carinskim referatima na graničnim prelazima prilikom kontrole ulaska i izlaska vozila i putnika iz carinskog područja BiH.',
    'Tačan odgovor prema izvornom dokumentu: Zaposlenim u carinskim referatima na graničnim prelazima prilikom kontrole ulaska i izlaska vozila i putnika iz carinskog područja BiH.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'upotreba', 'mobilnog', 'telefona', 'zabranjena', 'zaposlenim', 'carinskim', 'referatima', 'graničnim']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-047',
    'uio',
    'direct',
    'Zaposleni UIO na društvenim mrežama ne mogu objavljivati sljedeće sadržaje:',
    null,
    null,
    'Informacije do kojih su došli prilikom vršenja službene dužnosti, fotografije nastale na radnom mjestu i u objektima UIO, fotografije dokumenata, sadržaje koji imaju karakter govora mržnje, rasne, nacionalne, vjerske, rodne i druge netrpeljivosti.',
    'Tačan odgovor prema izvornom dokumentu: Informacije do kojih su došli prilikom vršenja službene dužnosti, fotografije nastale na radnom mjestu i u objektima UIO, fotografije dokumenata, sadržaje koji imaju karakter govora mržnje, rasne, nacionalne, vjerske, rodne i druge netrpeljivosti.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'društvenim', 'mrežama', 'objavljivati', 'sadržaje', 'informacije', 'kojih', 'došli']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-048',
    'uio',
    'direct',
    'Zaposleni u UIO koji smatra da se od njega ili od drugog zaposlenog traži da postupi na zakonit način ili način koji nije u skladu sa Kodeksom ponašanja zaposlenih u UIO o tome:',
    null,
    null,
    'Pismeno obavještava direktora UIO.',
    'Tačan odgovor prema izvornom dokumentu: Pismeno obavještava direktora UIO.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'zaposleni', 'smatra', 'njega', 'drugog', 'zaposlenog', 'traži', 'postupi', 'zakonit']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'uio-049',
    'uio',
    'direct',
    'Nepoštovanje Kodeksa ponašanja zaposlenih u UIO ima za posljedicu:',
    null,
    null,
    'Disciplinsku odgovornost.',
    'Tačan odgovor prema izvornom dokumentu: Disciplinsku odgovornost.',
    'PITANJA-SSS-OBJAVA-KONACNO: Organizacija UIO i prava i obaveze zaposlenih',
    'medium',
    array['uio', 'nepoštovanje', 'kodeksa', 'ponašanja', 'zaposlenih', 'posljedicu', 'disciplinsku', 'odgovornost']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-012',
    'kanc',
    'direct',
    'U osnovne knjige evidencija o predmetima i aktima organa uprave spada:',
    null,
    null,
    'Arhivska knjiga',
    'Tačan odgovor prema izvornom dokumentu: Arhivska knjiga',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'osnovne', 'knjige', 'evidencija', 'predmetima', 'aktima', 'organa', 'uprave', 'spada']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-013',
    'kanc',
    'direct',
    'U osnovne knjige evidencije o predmetima i aktima organa uprave spada:',
    null,
    null,
    'Djelovodnik za povjerljivu i strogo povjerljivu poštu.',
    'Tačan odgovor prema izvornom dokumentu: Djelovodnik za povjerljivu i strogo povjerljivu poštu.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'osnovne', 'knjige', 'evidencije', 'predmetima', 'aktima', 'organa', 'uprave', 'spada']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-014',
    'kanc',
    'direct',
    'U osnovne knjige evidencija o predmetima i aktima organa uprave spada:',
    null,
    null,
    'Upisnik prvostepenih predmeta upravnog postupka.',
    'Tačan odgovor prema izvornom dokumentu: Upisnik prvostepenih predmeta upravnog postupka.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'osnovne', 'knjige', 'evidencija', 'predmetima', 'aktima', 'organa', 'uprave', 'spada']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-015',
    'kanc',
    'direct',
    'U osnovne knjige evidencija o predmetima i aktima organa uprave spada:',
    null,
    null,
    'Upisnik prvostepenih predmeta upravnog postupka.',
    'Tačan odgovor prema izvornom dokumentu: Upisnik prvostepenih predmeta upravnog postupka.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'osnovne', 'knjige', 'evidencija', 'predmetima', 'aktima', 'organa', 'uprave', 'spada']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-016',
    'kanc',
    'direct',
    'U osnovne knjige evidencija o predmetima i aktima organa uprave spada:',
    null,
    null,
    'Upisnik drugostepenih predmeta upravnog postupka',
    'Tačan odgovor prema izvornom dokumentu: Upisnik drugostepenih predmeta upravnog postupka',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'osnovne', 'knjige', 'evidencija', 'predmetima', 'aktima', 'organa', 'uprave', 'spada']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-017',
    'kanc',
    'direct',
    'Upisnici se vode u vidu knjige:',
    null,
    null,
    'Sa tvrdim koricama.',
    'Tačan odgovor prema izvornom dokumentu: Sa tvrdim koricama.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'upisnici', 'vode', 'vidu', 'knjige', 'tvrdim', 'koricama']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-018',
    'kanc',
    'direct',
    'Djelovodnik se vodi u vidu knjige:',
    null,
    null,
    'Sa tvrdim koricama.',
    'Tačan odgovor prema izvornom dokumentu: Sa tvrdim koricama.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'djelovodnik', 'vodi', 'vidu', 'knjige', 'tvrdim', 'koricama']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-019',
    'kanc',
    'direct',
    'Apostile je ovjera isprave koja dokazuje:',
    null,
    null,
    'Vjerodostojnost isprave.',
    'Tačan odgovor prema izvornom dokumentu: Vjerodostojnost isprave.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'apostile', 'ovjera', 'isprave', 'dokazuje', 'vjerodostojnost']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-020',
    'kanc',
    'direct',
    'Poštu koja glasi na ime može otvoriti:',
    null,
    null,
    'Lice na čije ime glasi.',
    'Tačan odgovor prema izvornom dokumentu: Lice na čije ime glasi.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'poštu', 'glasi', 'otvoriti', 'lice', 'čije']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-021',
    'kanc',
    'direct',
    'Dostavnicu zaprimljenu uz koverat potpisuje:',
    null,
    null,
    'Zaposlenik ovlašten za prijem pošte.',
    'Tačan odgovor prema izvornom dokumentu: Zaposlenik ovlašten za prijem pošte.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'dostavnicu', 'zaprimljenu', 'koverat', 'potpisuje', 'zaposlenik', 'ovlašten', 'prijem', 'pošte']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-022',
    'kanc',
    'direct',
    'Pečat institucija Bosne i Hercegovine je:',
    null,
    null,
    'Oblika kruga.',
    'Tačan odgovor prema izvornom dokumentu: Oblika kruga.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'pečat', 'institucija', 'oblika', 'kruga']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-023',
    'kanc',
    'direct',
    'Sadržaj pečata institucija BiH kod diplomatsko-konzularnih predstavništava mora biti ispisana pored latiničnog i ćiriličnog pisma i na:',
    null,
    null,
    'Jeziku zemlje prijema.',
    'Tačan odgovor prema izvornom dokumentu: Jeziku zemlje prijema.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'sadržaj', 'pečata', 'institucija', 'diplomatsko', 'konzularnih', 'predstavništava', 'mora', 'biti']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-024',
    'kanc',
    'direct',
    'Pečat se po pravilu stavlja:',
    null,
    null,
    'S lijeve strane pored potpisa rukovodioca',
    'Tačan odgovor prema izvornom dokumentu: S lijeve strane pored potpisa rukovodioca',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'pečat', 'pravilu', 'stavlja', 'lijeve', 'strane', 'pored', 'potpisa', 'rukovodioca']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-025',
    'kanc',
    'direct',
    'Otprema povjerljive i strogo povjerljive pošte vrši se:',
    null,
    null,
    'Zapečaćeno.',
    'Tačan odgovor prema izvornom dokumentu: Zapečaćeno.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'otprema', 'povjerljive', 'strogo', 'pošte', 'vrši', 'zapečaćeno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-026',
    'kanc',
    'direct',
    'Akti koje treba hitno otpremiti drugim organima ili licima u istom mjestu, otpremaju se:',
    null,
    null,
    'Putem dostavljača-kurira.',
    'Tačan odgovor prema izvornom dokumentu: Putem dostavljača-kurira.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'akti', 'treba', 'hitno', 'otpremiti', 'drugim', 'organima', 'licima', 'istom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-027',
    'kanc',
    'direct',
    'Oznaka a/a u kartoteci ili skraćenom djelovodniku znači:',
    null,
    null,
    'Arhivirati predmet.',
    'Tačan odgovor prema izvornom dokumentu: Arhivirati predmet.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'oznaka', 'kartoteci', 'skraćenom', 'djelovodniku', 'znači', 'arhivirati', 'predmet']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-028',
    'kanc',
    'direct',
    'Oznaka priloga na aktu stavlja se:',
    null,
    null,
    'S lijeve strane ispod teksta u visini potpisa.',
    'Tačan odgovor prema izvornom dokumentu: S lijeve strane ispod teksta u visini potpisa.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'oznaka', 'priloga', 'aktu', 'stavlja', 'lijeve', 'strane', 'ispod', 'teksta']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-029',
    'kanc',
    'direct',
    'Skraćeni djelovodnik se zaključuje:',
    null,
    null,
    'Sa zvršetkom godine.',
    'Tačan odgovor prema izvornom dokumentu: Sa zvršetkom godine.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'skraćeni', 'djelovodnik', 'zaključuje', 'zvršetkom', 'godine']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-030',
    'kanc',
    'direct',
    'Kad se zaključuje djelovodnik mora se ovjeriti:',
    null,
    null,
    'Pečatom i potpisom radnika koji vodi djelovodnik.',
    'Tačan odgovor prema izvornom dokumentu: Pečatom i potpisom radnika koji vodi djelovodnik.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'zaključuje', 'djelovodnik', 'mora', 'ovjeriti', 'pečatom', 'potpisom', 'radnika', 'vodi']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-031',
    'kanc',
    'direct',
    'U rokovnik predmet se stavljaju:',
    null,
    null,
    'Nepotpuni predmeti u vezi kojih se mora obaviti neka radnja.',
    'Tačan odgovor prema izvornom dokumentu: Nepotpuni predmeti u vezi kojih se mora obaviti neka radnja.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'rokovnik', 'predmet', 'stavljaju', 'nepotpuni', 'predmeti', 'vezi', 'kojih', 'mora']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-032',
    'kanc',
    'direct',
    'Dostavljanje pošte vrši se po pravilu:',
    null,
    null,
    'Samo radnim danom.',
    'Tačan odgovor prema izvornom dokumentu: Samo radnim danom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'dostavljanje', 'pošte', 'vrši', 'pravilu', 'samo', 'radnim', 'danom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-033',
    'kanc',
    'direct',
    'U toku radnog dana, pošta se prima :',
    null,
    null,
    'Tokom cijelog radnog vremena.',
    'Tačan odgovor prema izvornom dokumentu: Tokom cijelog radnog vremena.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'toku', 'radnog', 'dana', 'pošta', 'prima', 'tokom', 'cijelog', 'vremena']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-034',
    'kanc',
    'direct',
    'Prijemni štambilj sadrži:',
    null,
    null,
    'Datum prijema.',
    'Tačan odgovor prema izvornom dokumentu: Datum prijema.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'prijemni', 'štambilj', 'sadrži', 'datum', 'prijema']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-035',
    'kanc',
    'direct',
    'Šta mora da sadrži službeni akt:',
    null,
    null,
    'Službeni akt (dopis) institucija BiH mora da sadrži: zaglavlje, naziv i adresu primaoca, kratku sadržinu predmeta, sadržaj akta, otisak službenog pečata i potpis ovlaštenog lica.',
    'Tačan odgovor prema izvornom dokumentu: Službeni akt (dopis) institucija BiH mora da sadrži: zaglavlje, naziv i adresu primaoca, kratku sadržinu predmeta, sadržaj akta, otisak službenog pečata i potpis ovlaštenog lica.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'mora', 'sadrži', 'službeni', 'dopis', 'institucija', 'zaglavlje', 'naziv', 'adresu']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-036',
    'kanc',
    'direct',
    'Prvostepeni predmeti upravnog postupka u kojim se upravni postupak pokreće po službenoj dužnosti ulažu se u omot označen:',
    null,
    null,
    'Plavom bojom.',
    'Tačan odgovor prema izvornom dokumentu: Plavom bojom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'prvostepeni', 'predmeti', 'upravnog', 'postupka', 'upravni', 'postupak', 'pokreće', 'službenoj']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-037',
    'kanc',
    'direct',
    'Prvostepeni predmeti upravnog postupka u kojim se upravni postupak pokreće po zahtjevu stranke ulažu se u omot označen:',
    null,
    null,
    'Zelenom bojom.',
    'Tačan odgovor prema izvornom dokumentu: Zelenom bojom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'prvostepeni', 'predmeti', 'upravnog', 'postupka', 'upravni', 'postupak', 'pokreće', 'zahtjevu']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-038',
    'kanc',
    'direct',
    'Predmeti koji se zavode u djelovodnik ulažu se u omot označen:',
    null,
    null,
    'Bijelom bojom.',
    'Tačan odgovor prema izvornom dokumentu: Bijelom bojom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'predmeti', 'zavode', 'djelovodnik', 'ulažu', 'omot', 'označen', 'bijelom', 'bojom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'kanc-039',
    'kanc',
    'direct',
    'Drugostepeni predmeti upravnog postupka u kojim se upravni postupak pokreće po zahtjevu stranke ulažu se u omot označen:',
    null,
    null,
    'Žutom bojom.',
    'Tačan odgovor prema izvornom dokumentu: Žutom bojom.',
    'PITANJA-SSS-OBJAVA-KONACNO: Kancelarijsko poslovanje',
    'medium',
    array['kanc', 'drugostepeni', 'predmeti', 'upravnog', 'postupka', 'upravni', 'postupak', 'pokreće', 'zahtjevu']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-026',
    'carine',
    'direct',
    'Rok važenja odobrenja za postupak unutrašnje obrade:',
    null,
    null,
    'do tri godine',
    'Tačan odgovor prema izvornom dokumentu: do tri godine',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'važenja', 'odobrenja', 'postupak', 'unutrašnje', 'obrade', 'godine']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-027',
    'carine',
    'direct',
    'Normativ proizvodnje u postupku unutrašnje obrade je:',
    null,
    null,
    'akt imaoca odobrenja za postupak unutrašnje obrade',
    'Tačan odgovor prema izvornom dokumentu: akt imaoca odobrenja za postupak unutrašnje obrade',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'normativ', 'proizvodnje', 'postupku', 'unutrašnje', 'obrade', 'imaoca', 'odobrenja', 'postupak']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-028',
    'carine',
    'direct',
    'Razdužni list za svaku pojedinu carinsku deklaraciju po kojoj je roba stavljena u postupak unutrašnje obrade imalac odobrenja podnosi:',
    null,
    null,
    'u roku od 30 dana od dana isteka roka za razduženje carinske deklaracije',
    'Tačan odgovor prema izvornom dokumentu: u roku od 30 dana od dana isteka roka za razduženje carinske deklaracije',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'razdužni', 'list', 'svaku', 'pojedinu', 'carinsku', 'deklaraciju', 'kojoj', 'roba']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-029',
    'carine',
    'direct',
    'Istanbulska konvencija (26. juni 1990.) je:',
    null,
    null,
    'konvencija o privremenom uvozu na osnovu karneta ATA',
    'Tačan odgovor prema izvornom dokumentu: konvencija o privremenom uvozu na osnovu karneta ATA',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'istanbulska', 'konvencija', 'juni', 'privremenom', 'uvozu', 'osnovu', 'karneta', 'ata']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-030',
    'carine',
    'direct',
    'Deklarant je:',
    null,
    null,
    'lice koje podnosi carinsku deklaraciju ili deklaraciju za privremeni smještaj u svoje ime ili lice u čije ime se podnosi carinska deklaracija ili deklaracija za privremeni smještaj',
    'Tačan odgovor prema izvornom dokumentu: lice koje podnosi carinsku deklaraciju ili deklaraciju za privremeni smještaj u svoje ime ili lice u čije ime se podnosi carinska deklaracija ili deklaracija za privremeni smještaj',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'deklarant', 'lice', 'podnosi', 'carinsku', 'deklaraciju', 'privremeni', 'smještaj', 'svoje']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-031',
    'carine',
    'direct',
    'Uvozne dažbine su:',
    null,
    null,
    'carina i druge dažbine sa jednakim efektom kao i carina',
    'Tačan odgovor prema izvornom dokumentu: carina i druge dažbine sa jednakim efektom kao i carina',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'uvozne', 'dažbine', 'carina', 'druge', 'jednakim', 'efektom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-032',
    'carine',
    'direct',
    'Jedinstvena carinska stopa može se primjeniti:',
    null,
    null,
    'na nekomercijalnu robu koja se nalazi u ličnom ptrljagu putnika, pod uslovom da carinska vrijednost robe koja podliježe plaćanju uvoznih dažbina ne prelazi 5.000,00 KM po putniku',
    'Tačan odgovor prema izvornom dokumentu: na nekomercijalnu robu koja se nalazi u ličnom ptrljagu putnika, pod uslovom da carinska vrijednost robe koja podliježe plaćanju uvoznih dažbina ne prelazi 5.000,00 KM po putniku',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'jedinstvena', 'carinska', 'stopa', 'primjeniti', 'nekomercijalnu', 'robu', 'nalazi', 'ličnom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-033',
    'carine',
    'direct',
    'Carinske formalnosti su:',
    null,
    null,
    'radnje koje preduzimaju lica i carinski organ u cilju primjene carinskih propisa',
    'Tačan odgovor prema izvornom dokumentu: radnje koje preduzimaju lica i carinski organ u cilju primjene carinskih propisa',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinske', 'formalnosti', 'radnje', 'preduzimaju', 'lica', 'carinski', 'organ', 'cilju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-034',
    'carine',
    'direct',
    'Privremeni smještaj je:',
    null,
    null,
    'situacija u kojoj je strana roba privremeno smještena pod carinski nadzor u periodu između predočenja carinskoj kancelariji i stavljanja u carinski odobreno postupanje ili upotrebu',
    'Tačan odgovor prema izvornom dokumentu: situacija u kojoj je strana roba privremeno smještena pod carinski nadzor u periodu između predočenja carinskoj kancelariji i stavljanja u carinski odobreno postupanje ili upotrebu',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'privremeni', 'smještaj', 'situacija', 'kojoj', 'strana', 'roba', 'privremeno', 'smještena']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-035',
    'carine',
    'direct',
    'Jednistvena carinska stopa može se primjeniti na robe koje se nalaze u pošiljkama:',
    null,
    null,
    'koje šalju fizičke osobe iz inostranstva fizičkim osobama u Bosni i Hercegovini, pod uslovom da su pošiljke povremene i da ne sadrže komercijalnu robu, te da carinska vrijednost robe koja podliježe plaćanju uvoznih dažbina ne prelazi 5.000,00 KM po pošiljci i da ih pošiljalac šalje primaocu bez bilo kakvog plaćanja',
    'Tačan odgovor prema izvornom dokumentu: koje šalju fizičke osobe iz inostranstva fizičkim osobama u Bosni i Hercegovini, pod uslovom da su pošiljke povremene i da ne sadrže komercijalnu robu, te da carinska vrijednost robe koja podliježe plaćanju uvoznih dažbina ne prelazi 5.000,00 KM po pošiljci i da ih pošiljalac šalje primaocu bez bilo kakvog plaćanja',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'jednistvena', 'carinska', 'stopa', 'primjeniti', 'robe', 'nalaze', 'pošiljkama', 'šalju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-036',
    'carine',
    'direct',
    'Carinska kontrola obuhvata:',
    null,
    null,
    'pregled robe',
    'Tačan odgovor prema izvornom dokumentu: pregled robe',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinska', 'kontrola', 'obuhvata', 'pregled', 'robe']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-037',
    'carine',
    'direct',
    'Za obračun i plaćanje indirektnih poreza za robu prijavljenu usmenim putem koja podliježe plaćanju indirektnih poreza carinski organ:',
    null,
    null,
    'putniku izdaje potvrdu o naplati indirektnih poreza za robu prijavljenu usmenim putem (CPD)',
    'Tačan odgovor prema izvornom dokumentu: putniku izdaje potvrdu o naplati indirektnih poreza za robu prijavljenu usmenim putem (CPD)',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'obračun', 'plaćanje', 'indirektnih', 'poreza', 'robu', 'prijavljenu', 'usmenim', 'putem']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-038',
    'carine',
    'direct',
    'Jedinstvena carinska stopa ne može se primjeniti na:',
    null,
    null,
    'robu koja prema Zakonu o akcizama u Bosni i Hercegovini podliježe obavezi obilježavanja akciznim markicama',
    'Tačan odgovor prema izvornom dokumentu: robu koja prema Zakonu o akcizama u Bosni i Hercegovini podliježe obavezi obilježavanja akciznim markicama',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'jedinstvena', 'carinska', 'stopa', 'primjeniti', 'robu', 'prema', 'zakonu', 'akcizama']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-039',
    'carine',
    'direct',
    'Jedinstevna carinska stopa neće se primjeniti:',
    null,
    null,
    'ako primalac pošiljke ili putnik zahtijeva da se obračun uvoznih dažbina izvrši po carinskoj stopi propisanoj u Carinskoj tarifi za robu sadržanu u pošiljci ili ličnom prtljagu putnika',
    'Tačan odgovor prema izvornom dokumentu: ako primalac pošiljke ili putnik zahtijeva da se obračun uvoznih dažbina izvrši po carinskoj stopi propisanoj u Carinskoj tarifi za robu sadržanu u pošiljci ili ličnom prtljagu putnika',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'jedinstevna', 'carinska', 'stopa', 'neće', 'primjeniti', 'primalac', 'pošiljke', 'putnik']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-040',
    'carine',
    'direct',
    'Oslobađanje od plaćanja uvoznih dažbina na ostalu robu nekomercijalnog karaktera sadržanu u ličnom prtljagu putnika odobrava se na:',
    null,
    null,
    'predmete u vrijednosti do 600,00 KM po putniku i danu, nezavisno od vrste prevoznog sredstva kojim putnik putuje',
    'Tačan odgovor prema izvornom dokumentu: predmete u vrijednosti do 600,00 KM po putniku i danu, nezavisno od vrste prevoznog sredstva kojim putnik putuje',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'oslobađanje', 'plaćanja', 'uvoznih', 'dažbina', 'ostalu', 'robu', 'nekomercijalnog', 'karaktera']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-041',
    'carine',
    'direct',
    'Putnik je dužan carinskom organu prijaviti svako unošenje i iznošenje gotovog novca u domaćoj ili stranoj valuti preko državne granice:',
    null,
    null,
    'u protivvrijednosti iznosa u konvertibilnim markama od 20.000,00 KM ili više',
    'Tačan odgovor prema izvornom dokumentu: u protivvrijednosti iznosa u konvertibilnim markama od 20.000,00 KM ili više',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'putnik', 'dužan', 'carinskom', 'organu', 'prijaviti', 'svako', 'unošenje', 'iznošenje']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-042',
    'carine',
    'direct',
    'Faktura je:',
    null,
    null,
    'trgovački dokument',
    'Tačan odgovor prema izvornom dokumentu: trgovački dokument',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'faktura', 'trgovački', 'dokument']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-043',
    'carine',
    'direct',
    'Usmenom carinskom deklaracijom može se prijaviti za postupak izvoza:',
    null,
    null,
    'roba nekomercijalnog karaktera',
    'Tačan odgovor prema izvornom dokumentu: roba nekomercijalnog karaktera',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'usmenom', 'carinskom', 'deklaracijom', 'prijaviti', 'postupak', 'izvoza', 'roba', 'nekomercijalnog']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-044',
    'carine',
    'direct',
    'Ne može se usmeno prijaviti:',
    null,
    null,
    'roba koja podliježe zabrani ili ograničenju',
    'Tačan odgovor prema izvornom dokumentu: roba koja podliježe zabrani ili ograničenju',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'usmeno', 'prijaviti', 'roba', 'podliježe', 'zabrani', 'ograničenju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-045',
    'carine',
    'direct',
    'Kao osiguranje za plaćanje carinskog duga u carinskim postupcima može se položiti:',
    null,
    null,
    'gotovinski depozit',
    'Tačan odgovor prema izvornom dokumentu: gotovinski depozit',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'osiguranje', 'plaćanje', 'carinskog', 'duga', 'carinskim', 'postupcima', 'položiti', 'gotovinski']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-046',
    'carine',
    'direct',
    'Osiguranje za plaćanje carinskog duga uključuje osiguranje plaćanja:',
    null,
    null,
    'svih propisanih uvoznih dažbina, poreza na dodatu vrijednost i drugih indirektnih poreza kojima, u skladu sa carinskim i drugim propisima, podliježe roba koja se uvozi',
    'Tačan odgovor prema izvornom dokumentu: svih propisanih uvoznih dažbina, poreza na dodatu vrijednost i drugih indirektnih poreza kojima, u skladu sa carinskim i drugim propisima, podliježe roba koja se uvozi',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'osiguranje', 'plaćanje', 'carinskog', 'duga', 'uključuje', 'plaćanja', 'svih', 'propisanih']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-047',
    'carine',
    'direct',
    'Lični predmeti i predmeti za sportske svrhe koje putnik privremeno unosi:',
    null,
    null,
    'su potpuno oslobođeni od plaćanja uvoznih dažbina i poreza na dodatu vrijednost',
    'Tačan odgovor prema izvornom dokumentu: su potpuno oslobođeni od plaćanja uvoznih dažbina i poreza na dodatu vrijednost',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'lični', 'predmeti', 'sportske', 'svrhe', 'putnik', 'privremeno', 'unosi', 'potpuno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-048',
    'carine',
    'direct',
    'Privremeni uvoz je carinski postupak kojim se dopušta upotreba strane robe:',
    null,
    null,
    'najduže dvije godine',
    'Tačan odgovor prema izvornom dokumentu: najduže dvije godine',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'privremeni', 'uvoz', 'carinski', 'postupak', 'dopušta', 'upotreba', 'strane', 'robe']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-049',
    'carine',
    'direct',
    'Robu uz djelimično oslobađanje od plaćanja uvoznih dažbina može da privremeno uveze:',
    null,
    null,
    'samo lice koje ispunjava uslove propisane carinskim propisima Bosne i Hercegovine',
    'Tačan odgovor prema izvornom dokumentu: samo lice koje ispunjava uslove propisane carinskim propisima Bosne i Hercegovine',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'robu', 'djelimično', 'oslobađanje', 'plaćanja', 'uvoznih', 'dažbina', 'privremeno', 'uveze']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-050',
    'carine',
    'direct',
    'Karnet ATA je:',
    null,
    null,
    'međunarodni carinski dokument za privremeni uvoz uz potpuno oslobađanje od plaćanja uvoznih dažbina',
    'Tačan odgovor prema izvornom dokumentu: međunarodni carinski dokument za privremeni uvoz uz potpuno oslobađanje od plaćanja uvoznih dažbina',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'karnet', 'ata', 'međunarodni', 'carinski', 'dokument', 'privremeni', 'uvoz', 'potpuno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-051',
    'carine',
    'direct',
    'CIM je:',
    null,
    null,
    'prevozna isprava koja se koristi u međunarodnom prevozu robe željeznicom',
    'Tačan odgovor prema izvornom dokumentu: prevozna isprava koja se koristi u međunarodnom prevozu robe željeznicom',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'cim', 'prevozna', 'isprava', 'koristi', 'međunarodnom', 'prevozu', 'robe', 'željeznicom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-052',
    'carine',
    'direct',
    'Odluku o visini stope kompenzatorne kamate donosi:',
    null,
    null,
    'Upravni odbor Uprave za indirektno oporezivanje',
    'Tačan odgovor prema izvornom dokumentu: Upravni odbor Uprave za indirektno oporezivanje',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'odluku', 'visini', 'stope', 'kompenzatorne', 'kamate', 'donosi', 'upravni', 'odbor']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-053',
    'carine',
    'direct',
    'Visina stope kompezatorne kamate iznosi:',
    null,
    null,
    '12%',
    'Tačan odgovor prema izvornom dokumentu: 12%',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'visina', 'stope', 'kompezatorne', 'kamate', 'iznosi']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-054',
    'carine',
    'direct',
    'Visina stope zatezne kamate za indirektne poreze iznosi:',
    null,
    null,
    '0,04 % za svaki dan zakašnjenja',
    'Tačan odgovor prema izvornom dokumentu: 0,04 % za svaki dan zakašnjenja',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'visina', 'stope', 'zatezne', 'kamate', 'indirektne', 'poreze', 'iznosi', 'svaki']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-055',
    'carine',
    'direct',
    'Pojednostavljeni postupak po fakturi je:',
    null,
    null,
    'pojednostavljeno prijavljivanje odobrene robe na graničnom prelazu',
    'Tačan odgovor prema izvornom dokumentu: pojednostavljeno prijavljivanje odobrene robe na graničnom prelazu',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'pojednostavljeni', 'postupak', 'fakturi', 'pojednostavljeno', 'prijavljivanje', 'odobrene', 'robe', 'graničnom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-056',
    'carine',
    'direct',
    'Roba koja se izvozi na osnovu izdatog odobrenja za pojednostavljeni postupak izvoza po fakturi može se izvesti iz carinskog područja Bosna i Hercegovina, preko:',
    null,
    null,
    'graničnih prelaza za međunarodni saobraćaj putnika i robe određenih odobrenjem',
    'Tačan odgovor prema izvornom dokumentu: graničnih prelaza za međunarodni saobraćaj putnika i robe određenih odobrenjem',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'roba', 'izvozi', 'osnovu', 'izdatog', 'odobrenja', 'pojednostavljeni', 'postupak', 'izvoza']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-057',
    'carine',
    'direct',
    'Da li je imalac odobrenja za pojednostavljeni postupak izvoza po fakturi dužan obezbjediti bankarsku garanciju ili drugi oblik osiguranja izvoznog carinskog duga koji bi mogao nastati za robu koju izvozi:',
    null,
    null,
    'nije dužan obezbjediti',
    'Tačan odgovor prema izvornom dokumentu: nije dužan obezbjediti',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'imalac', 'odobrenja', 'pojednostavljeni', 'postupak', 'izvoza', 'fakturi', 'dužan', 'obezbjediti']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-058',
    'carine',
    'direct',
    'Kako se određuje nadzorna carinska ispostava kod pojednostavljenog postupka po fakturi:',
    null,
    null,
    'prema sjedištu podnosioca zahtjeva',
    'Tačan odgovor prema izvornom dokumentu: prema sjedištu podnosioca zahtjeva',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'određuje', 'nadzorna', 'carinska', 'ispostava', 'pojednostavljenog', 'postupka', 'fakturi', 'prema']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-059',
    'carine',
    'direct',
    'Pojednostavljeni postupak po fakturi može se dobriti:',
    null,
    null,
    'za postupak izvoza, postupak puštanja robe u slobodan promet (osim za puštanje robe u slobodan promet: uz oslobađanje od plaćanja uvoznih dažbina i/ili drugih indirektnih poreza po bilo kom osnovu, uz povoljno tarifno postupanje i na osnovu tarifnih kvota)',
    'Tačan odgovor prema izvornom dokumentu: za postupak izvoza, postupak puštanja robe u slobodan promet (osim za puštanje robe u slobodan promet: uz oslobađanje od plaćanja uvoznih dažbina i/ili drugih indirektnih poreza po bilo kom osnovu, uz povoljno tarifno postupanje i na osnovu tarifnih kvota)',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'pojednostavljeni', 'postupak', 'fakturi', 'dobriti', 'izvoza', 'puštanja', 'robe', 'slobodan']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-060',
    'carine',
    'direct',
    'Dopunska carinska deklaracije podnosi se za:',
    null,
    null,
    'robu izvezenu/uvezenu po pojednostavljenim carinskim postupcima',
    'Tačan odgovor prema izvornom dokumentu: robu izvezenu/uvezenu po pojednostavljenim carinskim postupcima',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'dopunska', 'carinska', 'deklaracije', 'podnosi', 'robu', 'izvezenu', 'uvezenu', 'pojednostavljenim']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-061',
    'carine',
    'direct',
    'Zastupanje u carinskom postupku može biti:',
    null,
    null,
    'neposredno ili posredno',
    'Tačan odgovor prema izvornom dokumentu: neposredno ili posredno',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'zastupanje', 'carinskom', 'postupku', 'biti', 'neposredno', 'posredno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-062',
    'carine',
    'direct',
    'Carinski status robe znači:',
    null,
    null,
    'određenje statusa robe u smislu carinskih propisa kao domaće ili strane robe',
    'Tačan odgovor prema izvornom dokumentu: određenje statusa robe u smislu carinskih propisa kao domaće ili strane robe',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinski', 'status', 'robe', 'znači', 'određenje', 'statusa', 'smislu', 'carinskih']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-063',
    'carine',
    'direct',
    'U postupak privremenog uvoza može biti stavljena:',
    null,
    null,
    'strana roba',
    'Tačan odgovor prema izvornom dokumentu: strana roba',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'postupak', 'privremenog', 'uvoza', 'biti', 'stavljena', 'strana', 'roba']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-064',
    'carine',
    'direct',
    'Postupak spoljne obrade može se odobriti za:',
    null,
    null,
    'domaću robu koja se privremeno izvozi iz carinskog područja Bosne i Hercegovine radi procesa obrade',
    'Tačan odgovor prema izvornom dokumentu: domaću robu koja se privremeno izvozi iz carinskog područja Bosne i Hercegovine radi procesa obrade',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'postupak', 'spoljne', 'obrade', 'odobriti', 'domaću', 'robu', 'privremeno', 'izvozi']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-065',
    'carine',
    'direct',
    'Stopa poreza na dodatu vrijednost na uvoz dobara iznosi:',
    null,
    null,
    '17%',
    'Tačan odgovor prema izvornom dokumentu: 17%',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'stopa', 'poreza', 'dodatu', 'vrijednost', 'uvoz', 'dobara', 'iznosi']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-066',
    'carine',
    'direct',
    'Jedinstvena carinska isprava (JCI) je službeni obrazac koji se koristi:',
    null,
    null,
    'kao pisana (papirna) carinska deklaracija u redovnom postupku, u cilju stavljanja robe u neki od carinskih postupaka, kao i za ponovni izvoz robe iz carinskog područja Bosne i Hercegovine',
    'Tačan odgovor prema izvornom dokumentu: kao pisana (papirna) carinska deklaracija u redovnom postupku, u cilju stavljanja robe u neki od carinskih postupaka, kao i za ponovni izvoz robe iz carinskog područja Bosne i Hercegovine',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'jedinstvena', 'carinska', 'isprava', 'jci', 'službeni', 'obrazac', 'koristi', 'pisana']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-067',
    'carine',
    'direct',
    'Veterinarska kontrola kojoj podliježe određena roba koja se unosi u carinsko područje Bosne i Hercegovine obavlja se:',
    null,
    null,
    'na ulaznom graničnom prelazu za međunarodni saobraćaj robe i putnika I kategorije',
    'Tačan odgovor prema izvornom dokumentu: na ulaznom graničnom prelazu za međunarodni saobraćaj robe i putnika I kategorije',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'veterinarska', 'kontrola', 'kojoj', 'podliježe', 'određena', 'roba', 'unosi', 'carinsko']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-068',
    'carine',
    'direct',
    'Spoljnotrgovinski promet robe može obavljati:',
    null,
    null,
    'lice registrovano kod nadležnog organa u Bosni i Hercegovini i upisano u Jednstveni registar obveznika indirektnih poreza kod Uprave za indirektno oporezivanje po osnovu obavljanja spoljnotrgovinskog prometa',
    'Tačan odgovor prema izvornom dokumentu: lice registrovano kod nadležnog organa u Bosni i Hercegovini i upisano u Jednstveni registar obveznika indirektnih poreza kod Uprave za indirektno oporezivanje po osnovu obavljanja spoljnotrgovinskog prometa',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'spoljnotrgovinski', 'promet', 'robe', 'obavljati', 'lice', 'registrovano', 'nadležnog', 'organa']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-069',
    'carine',
    'direct',
    'Poslove zastupanja u carinskom postupku u smislu člana 5. i 6. Zakona o carinskoj politici u Bosni i Hercegovini može obavljati:',
    null,
    null,
    'lice registrovano kod nadležnog organa u Bosni i Hercegovini i upisano u Jednstveni registar obveznika indirektnih poreza kod Uprave za indirektno oporezivanje po osnovu obavljanja spoljnotrgovinskog prometa i po osnovu obavljanja poslova međunarodne špedicije i da ima ovlaštenje te Uprave za pristup carinskom informacionom podsistemu',
    'Tačan odgovor prema izvornom dokumentu: lice registrovano kod nadležnog organa u Bosni i Hercegovini i upisano u Jednstveni registar obveznika indirektnih poreza kod Uprave za indirektno oporezivanje po osnovu obavljanja spoljnotrgovinskog prometa i po osnovu obavljanja poslova međunarodne špedicije i da ima ovlaštenje te Uprave za pristup carinskom informacionom podsistemu',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'poslove', 'zastupanja', 'carinskom', 'postupku', 'smislu', 'člana', 'zakona', 'carinskoj']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-070',
    'carine',
    'direct',
    'Karnet ATA ne može se koristiti:',
    null,
    null,
    'za privremeni uvoz prevoznih sredstava',
    'Tačan odgovor prema izvornom dokumentu: za privremeni uvoz prevoznih sredstava',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'karnet', 'ata', 'koristiti', 'privremeni', 'uvoz', 'prevoznih', 'sredstava']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-071',
    'carine',
    'direct',
    'Karnet ATA važi:',
    null,
    null,
    'godinu dana od dana izdavanja',
    'Tačan odgovor prema izvornom dokumentu: godinu dana od dana izdavanja',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'karnet', 'ata', 'važi', 'godinu', 'dana', 'izdavanja']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-072',
    'carine',
    'direct',
    'Uvjerenje o odobrenju vozila za prevoz pod karnetom TIR mora biti važeće:',
    null,
    null,
    'do kraja prevozne operacije koja se odvija uz primjenu karneta TIR',
    'Tačan odgovor prema izvornom dokumentu: do kraja prevozne operacije koja se odvija uz primjenu karneta TIR',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'uvjerenje', 'odobrenju', 'vozila', 'prevoz', 'karnetom', 'tir', 'mora', 'biti']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-073',
    'carine',
    'direct',
    'Carinski postupak provoza je carinski postupak koji se koristi kako bi se olakšalo kretanje robe između:',
    null,
    null,
    'dvije tačke jednistvenog carinskog područja, preko drugog carinskog područja i između dva ili više carinskih područja',
    'Tačan odgovor prema izvornom dokumentu: dvije tačke jednistvenog carinskog područja, preko drugog carinskog područja i između dva ili više carinskih područja',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinski', 'postupak', 'provoza', 'koristi', 'olakšalo', 'kretanje', 'robe', 'između']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-074',
    'carine',
    'direct',
    'Carinski postupak provoza sprovodi se:',
    null,
    null,
    'bez naplate carine i drugih dažbina, pod uslovom da se ispune svi propisani zahtjevi koji se odnose na poštivanje rokova, predočenje robe, osiguranje duga, carinska obilježja',
    'Tačan odgovor prema izvornom dokumentu: bez naplate carine i drugih dažbina, pod uslovom da se ispune svi propisani zahtjevi koji se odnose na poštivanje rokova, predočenje robe, osiguranje duga, carinska obilježja',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinski', 'postupak', 'provoza', 'sprovodi', 'naplate', 'drugih', 'dažbina', 'uslovom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-075',
    'carine',
    'direct',
    'Carinskim postupkom provoza dozvoljava se kretanje sljedeće robe:',
    null,
    null,
    'domaće i strane robe',
    'Tačan odgovor prema izvornom dokumentu: domaće i strane robe',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinskim', 'postupkom', 'provoza', 'dozvoljava', 'kretanje', 'robe', 'domaće', 'strane']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-076',
    'carine',
    'direct',
    'Carinske formalnosti kod kretanja robe u postupku provoza obavljaju se pod pokrićem različitih transportnih papirnih dokumenata u zavisnosti od vrste transporta:',
    null,
    null,
    'TIR i ATA karneta, JCI obrasca, CIM tovarnog lista, NATO 302 obrasca i svakog drugog dokumenta predviđenog međunarodnim sporazumom koji je prihvatila Bosna i Hercegovina',
    'Tačan odgovor prema izvornom dokumentu: TIR i ATA karneta, JCI obrasca, CIM tovarnog lista, NATO 302 obrasca i svakog drugog dokumenta predviđenog međunarodnim sporazumom koji je prihvatila Bosna i Hercegovina',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinske', 'formalnosti', 'kretanja', 'robe', 'postupku', 'provoza', 'obavljaju', 'pokrićem']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-077',
    'carine',
    'direct',
    'Carinske formalnosti kod kretanja robe u postupku provoza obavljaju se pomoću tehnike za elektronsku obradu podataka, koristeći novi kompjuerizovani tranzitni sistem, za koji se koristi sljedeća skraćenica:',
    null,
    null,
    'NCTS',
    'Tačan odgovor prema izvornom dokumentu: NCTS',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinske', 'formalnosti', 'kretanja', 'robe', 'postupku', 'provoza', 'obavljaju', 'pomoću']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-078',
    'carine',
    'direct',
    'Korisnik postupka provoza dužan je podnijeti provoznu carinsku deklaraciju:',
    null,
    null,
    'polaznoj carinskoj kancelariji',
    'Tačan odgovor prema izvornom dokumentu: polaznoj carinskoj kancelariji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'korisnik', 'postupka', 'provoza', 'dužan', 'podnijeti', 'provoznu', 'carinsku', 'deklaraciju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-079',
    'carine',
    'direct',
    'Carinski postupak provoza sprovodi se u sljedećim carinskim kancelarijama:',
    null,
    null,
    'polaznoj, provoznoj i odredišnoj carinskoj kancelariji',
    'Tačan odgovor prema izvornom dokumentu: polaznoj, provoznoj i odredišnoj carinskoj kancelariji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinski', 'postupak', 'provoza', 'sprovodi', 'sljedećim', 'carinskim', 'kancelarijama', 'polaznoj']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-080',
    'carine',
    'direct',
    'Carinski postupak provoza, bez nepravilnosti, završava se u sljedećoj carinskoj kancelariji:',
    null,
    null,
    'odredišnoj carinskoj kancelariji',
    'Tačan odgovor prema izvornom dokumentu: odredišnoj carinskoj kancelariji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'carinski', 'postupak', 'provoza', 'nepravilnosti', 'završava', 'sljedećoj', 'carinskoj', 'kancelariji']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-081',
    'carine',
    'direct',
    'Lice koje podnosi osiguranje (garanciju) za mogući dug u postupku provoza je:',
    null,
    null,
    'korisnik postupka provoza',
    'Tačan odgovor prema izvornom dokumentu: korisnik postupka provoza',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'lice', 'podnosi', 'osiguranje', 'garanciju', 'mogući', 'postupku', 'provoza', 'korisnik']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-082',
    'carine',
    'direct',
    'Osiguranje za mogući dug u postupku provoza može biti:',
    null,
    null,
    'pojedinačno i sveobuhvatno',
    'Tačan odgovor prema izvornom dokumentu: pojedinačno i sveobuhvatno',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'osiguranje', 'mogući', 'postupku', 'provoza', 'biti', 'pojedinačno', 'sveobuhvatno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-083',
    'carine',
    'direct',
    'Sveobuhvatno osiguranje u postupku provoza u obliku preuzete obaveze jamca (garanta), pokriva mogući dug za:',
    null,
    null,
    'više postupaka provoza',
    'Tačan odgovor prema izvornom dokumentu: više postupaka provoza',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'sveobuhvatno', 'osiguranje', 'postupku', 'provoza', 'obliku', 'preuzete', 'obaveze', 'jamca']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-084',
    'carine',
    'direct',
    'Postupak provoza koji se zasniva na korišćenju pisanih (papirnih) dokumenata u slučaju kada nije moguće primjeniti elektonski sistem provoza, naziva se:',
    null,
    null,
    'rezervni postupak provoza',
    'Tačan odgovor prema izvornom dokumentu: rezervni postupak provoza',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'postupak', 'provoza', 'zasniva', 'korišćenju', 'pisanih', 'papirnih', 'dokumenata', 'slučaju']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-085',
    'carine',
    'direct',
    'Prepoznavanje i istovjetnost robe u postupku provoza obezbjeđuje se:',
    null,
    null,
    'stavljanjem carinske plombe ili preciznim opisom robe u provoznoj carinskoj deklaraciji',
    'Tačan odgovor prema izvornom dokumentu: stavljanjem carinske plombe ili preciznim opisom robe u provoznoj carinskoj deklaraciji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'prepoznavanje', 'istovjetnost', 'robe', 'postupku', 'provoza', 'obezbjeđuje', 'stavljanjem', 'carinske']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-086',
    'carine',
    'direct',
    'Rok predaje robe u postupku provoza je:',
    null,
    null,
    'datum do kada roba i prateća dokumentacija trebaju biti predočeni odredišnoj carinskoj kancelariji',
    'Tačan odgovor prema izvornom dokumentu: datum do kada roba i prateća dokumentacija trebaju biti predočeni odredišnoj carinskoj kancelariji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'predaje', 'robe', 'postupku', 'provoza', 'datum', 'roba', 'prateća', 'dokumentacija']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-087',
    'carine',
    'direct',
    'Postupak izvoza u koji je izvozno ocarinjena roba puštena završava se:',
    null,
    null,
    'kada roba stvarno fizički istupi iz carinskog područja Bosne i Hercegovine u nepromijenjenom stanju',
    'Tačan odgovor prema izvornom dokumentu: kada roba stvarno fizički istupi iz carinskog područja Bosne i Hercegovine u nepromijenjenom stanju',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'postupak', 'izvoza', 'izvozno', 'ocarinjena', 'roba', 'puštena', 'završava', 'stvarno']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-088',
    'carine',
    'direct',
    'Usmena carinska deklaracija za izvoz robe može se podnijeti:',
    null,
    null,
    'samo u izlaznoj carinskoj kancelariji',
    'Tačan odgovor prema izvornom dokumentu: samo u izlaznoj carinskoj kancelariji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'usmena', 'carinska', 'deklaracija', 'izvoz', 'robe', 'podnijeti', 'samo', 'izlaznoj']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-089',
    'carine',
    'direct',
    'Pregled robe u carinskim postupcima može biti:',
    null,
    null,
    'potpuni ili djelimični',
    'Tačan odgovor prema izvornom dokumentu: potpuni ili djelimični',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'pregled', 'robe', 'carinskim', 'postupcima', 'biti', 'potpuni', 'djelimični']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-090',
    'carine',
    'direct',
    'Pregledu robe ima pravo da prisustvuje:',
    null,
    null,
    'deklarant ili njegov ovlašteni zastupnik',
    'Tačan odgovor prema izvornom dokumentu: deklarant ili njegov ovlašteni zastupnik',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'pregledu', 'robe', 'pravo', 'prisustvuje', 'deklarant', 'njegov', 'ovlašteni', 'zastupnik']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-091',
    'carine',
    'direct',
    'Bescarinska prodavnica može se nalaziti:',
    null,
    null,
    'samo u onom dijelu bh. aerodroma određenom za tranzit ili odlazak putnika u međunarodnom vazdušnom saobraćaju',
    'Tačan odgovor prema izvornom dokumentu: samo u onom dijelu bh. aerodroma određenom za tranzit ili odlazak putnika u međunarodnom vazdušnom saobraćaju',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'bescarinska', 'prodavnica', 'nalaziti', 'samo', 'onom', 'dijelu', 'aerodroma', 'određenom']::text[],
    '2026.06.05-split-50-130'
  ),
  (
    'car-092',
    'carine',
    'direct',
    'MRN broj je:',
    null,
    null,
    'glavni referentni broj je registarski broj koji dodjeljuje nadležna carinska kancelarija carinskoj deklaraciji',
    'Tačan odgovor prema izvornom dokumentu: glavni referentni broj je registarski broj koji dodjeljuje nadležna carinska kancelarija carinskoj deklaraciji',
    'PITANJA-SSS-OBJAVA-KONACNO: Pitanja iz oblasti carinskih postupaka',
    'medium',
    array['carine', 'mrn', 'broj', 'glavni', 'referentni', 'registarski', 'dodjeljuje', 'nadležna', 'carinska']::text[],
    '2026.06.05-split-50-130'
  )
on conflict (id) do update set
  category_id = excluded.category_id,
  question_type = excluded.question_type,
  question = excluded.question,
  options = excluded.options,
  answer_index = excluded.answer_index,
  answer = excluded.answer,
  rationale = excluded.rationale,
  source = excluded.source,
  difficulty = excluded.difficulty,
  keywords = excluded.keywords,
  content_version = excluded.content_version,
  updated_at = now();
